function SkopeReport(this)
% report parameters relevant to skope
rep = { [ sprintf('Skope relevant parameters:\n'),...
             sprintf('   Skope interleave TR (ms):   %.1f\n',1e3* this.seq_params.skopeInterleaveTR),...
             sprintf('   Skope acq duration (ms):   %.1f\n',1e3* this.seq_params.skopeAcqDuration),...
             sprintf('   Prescan sync events:   %g\n',this.seq_params.nPrescans),...
             sprintf('   Number of dynamics:   %d\n',this.seq_params.nDynamics),...
             sprintf('   Number of interleaves:   %d\n', this.seq_params.nInterleaves)],...
           [ sprintf('Other parameters:\n'),...
             sprintf('TE (ms): %.1f\n',1e3* this.seq_params.TE),...
             sprintf('TR (ms): %.1f\n',1e3* this.seq_params.TR) ] };

fprintf([rep{:}]);
end